server:
  port: 8083 # Puerto asignado para el microservicio de clientes

spring:
  application:
    name: ms-usuarios # Nombre con el que se registrará en el panel de Eureka

  # ===================================
  # Configuración de Rendimiento
  # ===================================
  threads:
    virtual:
      enabled: true # Aprovecha los hilos virtuales de tu JDK moderno

  mvc:
    problemdetails:
      enabled: false # Desactivado para usar tu GlobalExceptionHandler personalizado

  # ===================================
  # Conexión a PostgreSQL (NeonTech)
  # ===================================
  datasource:
    url: jdbc:postgresql://ep-twilight-heart-acf1szz7-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_pCkU9F6jWoZT
    driver-class-name: org.postgresql.Driver

    # Pool de conexiones optimizado para el plan gratuito de Neon
    hikari:
      maximum-pool-size: 3

  # ===================================
  # Configuración de Hibernate / JPA
  # ===================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Creará las tablas automáticamente (Usuario, Perfil, etc.)
    show-sql: true # Muestra las consultas en consola
    properties:
      hibernate:
        format_sql: true # Formatea el SQL para que sea legible

# ===================================
# Configuración del Cliente Eureka
# ===================================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-wp64.onrender.com/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    # ─── AGREGA ESTA LÍNEA CRUCIAL ───
    non-secure-port: 80
  instance:
    # 2. Desactivamos el uso de IP interna
    prefer-ip-address: false
    # 3. Le decimos que use el hostname que Render le asigna (si existe), o localhost en local
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    # ===================================
# Configuración de Seguridad y JWT
feign:
  client:
    config:
      ms-clientes:
        loggerLevel: full
jwt:
  # Esta es una clave secreta generada en Hexadecimal (Mínimo 256 bits requeridos por seguridad)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # Tiempo de vida del token en milisegundos (86400000 ms = 1 día)
  expiration: 86400000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html