server:
  port: ${PORT:8083}

spring:
  application:
    name: ms-usuarios

  # ===================================
  # Configuración de Rendimiento
  # ===================================
  threads:
    virtual:
      enabled: true

  mvc:
    problemdetails:
      enabled: false

  # ===================================
  # Conexión a PostgreSQL (NeonTech)
  # ===================================
  datasource:
    url: jdbc:postgresql://ep-twilight-heart-acf1szz7-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_pCkU9F6jWoZT
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3

  # ===================================
  # Configuración de Hibernate / JPA
  # ===================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ===================================
# Configuración del Cliente Eureka
# ===================================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-wp64.onrender.com/eureka/

  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}

    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false

    home-page-url: https://${RENDER_EXTERNAL_HOSTNAME}/
    status-page-url: https://${RENDER_EXTERNAL_HOSTNAME}/actuator/info
    health-check-url: https://${RENDER_EXTERNAL_HOSTNAME}/actuator/health

# ===================================
# Configuración de Seguridad y JWT
# ===================================
feign:
  client:
    config:
      ms-clientes:
        loggerLevel: full

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# ===================================
# Swagger
# ===================================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html